# Generated by Django 3.2.6 on 2022-03-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
