# Generated by Django 3.2.6 on 2022-03-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0004_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
