# Generated by Django 3.2.6 on 2022-04-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0007_viewstraffic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewstraffic',
            name='traffic',
        ),
    ]
